---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[common]
      - recipe[useraccounts]
      - recipe[unattended-upgrades]
      - recipe[aws_codedeploy]
      - recipe[aws_cloudwatch]
      - recipe[aws_ssm]
      - recipe[web]
      - recipe[prepare]
    attributes:
