---

# Create a server base AMI

- name: Server base AMI
  hosts: 127.0.0.1
  connection: local
  become: true
  roles:
    - common
    - unattended_upgrades
    - useraccounts
    - aws_ssm
    - aws_codedeploy
    - security
