name 'aws_ssm'
description 'Installs the AWS SSM agent'
maintainer 'Codemonauts Ops'
maintainer_email 'crew@codemonauts.com'
source_url 'https://github.com/codemonauts/ami-baseimage/'
issues_url 'https://github.com/codemonauts/aws-baseimage/issues'
chef_version '>= 12.4'
supports 'debian'
supports 'ubuntu'
license 'Apache-2.0'
version '1.0.0'

depends 'line'
