---

# Install and remove common packages needed for support

- name: Install packages needed
  ansible.builtin.apt:
    name:
      - vim-tiny
      - apt-transport-https
      - bash-completion
      - curl
      - htop
      - less
      - ncdu
      - tmux
      - psmisc
      - cron
      - logrotate
      - locales
      - lsb-release
      - ca-certificates
    update_cache: true

- name: Remove unused packages
  ansible.builtin.apt:
    name:
      - man-db
      - manpages
      - manpages-dev
    state: absent
    autoremove: true
    purge: true

# locales

- name: Copy locales config
  ansible.builtin.copy:
    src: locale.gen
    dest: /etc/locale.gen
    owner: root
    group: root
    mode: '0644'

- name: Generate locales for en_US and de_DE
  ansible.builtin.command: locale-gen
  changed_when: true

# resolve instance data

- name: Add mappings to /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      169.254.169.254 instance-data
      fd00:ec2::254 instance-data
