---

# Install php

- name: Add ondrej php repo
  ansible.builtin.apt_repository:
    repo: "ppa:ondrej/php"
    codename: jammy

- name: "Install packages for php {{ php_version }}"
  ansible.builtin.apt:
    name:
      - "php{{ php_version }}-bcmath"
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-imagick"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-opcache"
      - "php{{ php_version }}-soap"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-zip"

- name: Delete default files
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
    - "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
