---
name: Validate

on: [push] # yamllint disable-line rule:truthy

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate provisioning
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Init base image
        run: "packer init baseimage.pkr.hcl"

      - name: Init webserver image
        run: "packer init webserver.pkr.hcl"

      - name: Validate base image
        run: "packer validate baseimage.pkr.hcl"

      - name: Validate packer configuration
        run: "packer validate webserver.pkr.hcl"

      - name: Validate YAML
        uses: ibiqlik/action-yamllint@v3

      - name: Validate ansible playbooks
        uses: ansible/ansible-lint-action@main
