name: Validate

on:
  - push

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate provisioning
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Init packer 
        run: "packer init packer.pkr.hcl"

      - name: Validate packer configuration
        run: "packer validate packer.pkr.hcl"

      - name: Validate ansible playbooks
        uses: ansible/ansible-lint-action@main