name: packer

on:
  - push

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer and Cookstyle
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - run: "packer init"

      - run: "packer validate packer.pkr.hcl"

      - name: Install CINC workstation
        run: curl -L https://omnitruck.cinc.sh/install.sh | sudo bash -s -- -P cinc-workstation -v 22


      - name: Run Cookstyle
        run: cookstyle
